### ISSUE TITLE
求问startcode可以在哪里找到

### ISSUE THREAD

**Issue by foreverpiano** [PKUFlyingPig/GameOfLife#1]
cs61C上写的clone Student的git但他是private repo没有权限

**Comment by foreverpiano** [comment]
再问一下是不是部分课程的视频是没有比如说 UCB CS126 是不是只有教材没有课程？

**Comment by foreverpiano** [comment]
> cs61C上写的clone Student的git但他是private repo没有权限

https://inst.eecs.berkeley.edu/~cs61c/fa20/projects/proj1/ 指这个

**Comment by PKUFlyingPig** [comment]
https://github.com/61c-teach/fa20-proj1-starter.git 这个repo是公开的，它那个文档里的意思是让学生自己建一个私有的repo，然后把这个公开的repo作为remote的repo进行pull。你可以直接clone它这个公开的repo。

**Comment by PKUFlyingPig** [comment]
> 再问一下是不是部分课程的视频是没有比如说 UCB CS126 是不是只有教材没有课程？

是的，部分课程是没有视频的。

**Comment by foreverpiano** [comment]
感谢
